### ISSUE TITLE
Tree View Sample: Remove Example Hard Coding Sensitive Information

### ISSUE THREAD

**Issue by clarkio** [Microsoft/vscode-extension-samples#139]
In the tree view sample, specifically in the FTP Explorer solution, there is code that seems to promote storing sensitive information directly in it. If I'm understanding the code correctly I believe this should be avoided so that other extension authors don't think it's safe to follow this practice.

Here is the exact code: https://github.com/Microsoft/vscode-extension-samples/blob/master/tree-view-sample/src/ftpExplorer.ts#L158

Let me know your thoughts on this. I also am hoping there may be documentation or a different example that can help show how to store sensitive data to be used within extensions such as this FTP example.

**Comment by sandy081** [comment]
@clarkio Agreed this is not correct way to have login details. This is an example demonstrating how to use custom tree view api and hence login was not given importance. I am sure users going through this sample will understand that. There are different ways how you can get login details and since this example does not meant for this probably I would just an add comment to the line saying that this login details were hardcoded for an example purpose.

**Comment by clarkio** [comment]
Totally understand and agree a code comment is acceptable to at least raise awareness not to follow the example when it comes to storing and using sensitive data. Thanks @sandy081
