### ISSUE TITLE
Could when expression match resource path?

### ISSUE THREAD

**Issue by taoqf** [microsoft/vscode-extension-samples#140]
I have file: a.ts, b/a.ts, and I want show a explorer context menu on a.ts, not on b/a.ts, How can I do this?
I could not find any clue in <https://code.visualstudio.com/docs/getstarted/keybindings#_when-clause-contexts>, I hope I could get some help here.

**Comment by isidorn** [comment]
Not currently possible, we only have a `resourceFilename` which is similar but can not do what you want, since it is scoped to the name.
We do not have a key that would have the value of the full path.
If more users ask for this we could introduce it.

Code pointer https://github.com/Microsoft/vscode/blob/0742a095ba03903189b779ed1d76337c26eaaea4/src/vs/workbench/common/resources.ts#L14
