### ISSUE TITLE
Extension causes high cpu load

### ISSUE THREAD

**Issue by rafaelsous** [Microsoft/vscode-extension-samples#169]
- Issue Type: `Performance`
- Extension Name: `qlk-vscode`
- Extension Version: `0.1.4`
- OS Version: `Linux x64 4.15.0-46-generic`
- VSCode version: `1.32.3`

:warning: Make sure to **attach** this file from your *home*-directory: `/home/rafael/ash9g.qlk-vscode-unresponsive.cpuprofile.txt` :warning:

Find more details here: https://github.com/Microsoft/vscode/wiki/Explain:-extension-causes-high-cpu-load

**Comment by Tyriar** [comment]
Report the issue against the problem extension, this repo is just sample code for extension authors.

**Comment by Tyriar** [comment]
Ok I see what the problem is, they have this repo linked in the marketplace/package.json. It looks like https://github.com/graytware/vscode-extension-samples might have been the original repo but it doesn't exist (or the user). FYI @jrieken, not sure we can do anything about this but it's not the first time https://github.com/Microsoft/vscode-extension-samples/issues?q=is%3Aissue+qlk-vscode+is%3Aclosed
