### ISSUE TITLE
Question: how to support i18n while writing extension for vscode?

### ISSUE THREAD

**Issue by leftstick** [Microsoft/vscode-extension-samples#20]
Sorry for asking it here, because I cannot get answer from [stackoverflow](https://stackoverflow.com/questions/44668055/how-to-support-i18n-while-writing-extension-for-vscode)

I'm working on an extension authoring, a few menu items will be shown in explorer view, as below:

![screen shot 2017-06-22 at 4 52 21 pm](https://user-images.githubusercontent.com/1059956/27425516-4361a712-576b-11e7-823d-f636055b7625.png)

I am wondering if it is possible to give them localization such as all other built-in menus items?

**Comment by leftstick** [comment]
@michelkaporin checked the module, i am not sure my understanding is correct. 

For example, i have following `command` definition in the `package.json`:

```javascript
"commands": [
      {
        "command": "favorites.addToFavorites",
        "title": "%command.favorites.addtofavorites%"
      },
      {
        "command": "favorites.deleteFavorite",
        "title": "%command.favorites.deletefavorite%"
      }
    ]
```

So i give a default value for it in `package.nls.json` as below:

```javascript
{
	"command.favorites.addtofavorites": "Add to Favorites",
	"command.favorites.deletefavorite": "Delete favorite"
}
```

If i need a `zh-CN` translation, what should i do? Thanks very much

**Comment by michelkaporin** [comment]
@leftstick As a next step you need to perform translations. We use Transifex platform for this as I have already mentioned above. How to onboard your extension to it (in terms of code) is described here:
https://github.com/Microsoft/vscode-nls-dev#onboarding-extension-to-transifex

If you want to manually translate your extension, you should reuse the same code as in the example there but without calling `nls.pushXlfFiles` and `nls.pullXlfFiles`. Instead you will pipe the result of `prepareXlfFiles` to your filesystem and work with XLF standard for translation. Once you have translated XLF files you pipe them to `nls.prepareJsonFiles` and then to `./i18n` folder in the root of your extension.

Hope it makes sense.

**Comment by leftstick** [comment]
@michelkaporin make sense. Thanks a lot.  Last question, i have `i18n` folder generated:

![screen shot 2017-06-23 at 5 28 35 pm](https://user-images.githubusercontent.com/1059956/27475927-6d5e366a-5839-11e7-8852-b7f87c8745f8.png)


But when i start debugging my extension, the menu item still display in english, while the rest built-in menus have been changed correctly(I have chagned the `locale.json` to `"locale":"zh-CN"`)

![screen shot 2017-06-23 at 5 30 13 pm](https://user-images.githubusercontent.com/1059956/27475998-a5894cc8-5839-11e7-985d-a8efef99cbcf.png)

**Comment by michelkaporin** [comment]
Check if `package.i18n.json` contains your translations. If yes, then I am not sure what's wrong. If not, then translations most likely were not correctly imported.

**Comment by leftstick** [comment]
Hi @michelkaporin, thanks for your quick response.

Content in `package.i18n.json` is correctly generated:

![screen shot 2017-06-23 at 9 50 43 pm](https://user-images.githubusercontent.com/1059956/27485124-1b0f8e52-585e-11e7-989a-6dcbcc5944d4.png)

It's indeed weird

**Comment by michelkaporin** [comment]
Maybe you need to create vsix to see all localizations. @dbaeumer should know more.

**Comment by leftstick** [comment]
@michelkaporin, thanks anyway. I am going to do more trials with my extension.

**Comment by dbaeumer** [comment]
Translation bundling in a build time step in VS Code not a development time step. We do this to optimize translations in terms of size and key look up. So if you want to test the translation of an extension you need to built a vsix and install it locally. It is the same with VS Code. If run out of source you don't see any translated values even if you switch to another language.

**Comment by leftstick** [comment]
@dbaeumer  thanks for your answer. I tried following:

1. generate `.vsix` with `vsce package`
2. use `Install from VSIX...`
3. reload `vscode`
4. change language to `zh-CN`
5. reload `vscode`
6. translation is not there, even the rest menus were changed

So i tried `vsce ls` to see if my `i18n` stuff packaged, and i got:

```bash
.esformatter
gulpfile.js
i18n/chs/package.i18n.json
images/favorites.png
images/preview.gif
LICENSE
out/src/enum/index.js
out/src/index.js
out/src/model/index.js
out/src/provider/FavoritesProvider.js
package-lock.json
package.json
package.nls.json
README.md
```

The third line tells that the `i18n` stuff were package correctly. 

I tried to search it there is extension provided such experience(as example for me), but no luck. Thanks anyway

**Comment by michelkaporin** [comment]
@dbaeumer let me know if there is something wrong on my side, then I will jump in. Leaving it to you for now.

**Comment by leftstick** [comment]
I found even the built-in extension `vscode-node-debug` has this issue either. So i reported there [Localization for menu items seem not working properly](https://github.com/Microsoft/vscode-node-debug/issues/151)

**Comment by michelkaporin** [comment]
@leftstick check if your `nls` import and configuration is done before you import any other code in your extension.

**Comment by leftstick** [comment]
@michelkaporin  just tried by your advice, import `nls` and `config` it at the very beginning of the extension entry point. Rebuild it with `vsce package`, install this `VSIX` from local. But no luck, the menu item still displayed in English

![screen shot 2017-06-29 at 9 35 58 am](https://user-images.githubusercontent.com/1059956/27667713-43dd5b84-5caf-11e7-9e52-4bd69a8ce6eb.png)

**Comment by vazexqi** [comment]
@leftstick - From what you posted at https://github.com/Microsoft/vscode-extension-samples/issues/20#issuecomment-311006385 it doesn't seem like you have the right .json files in your out folder.

Documentation on this is quite sparse, but from inspecting what is in

1. /Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/extensions/markdown 
1. https://github.com/Microsoft/vscode-nls/blob/master/src/tests/localize.test.ts#L60
1. https://github.com/Microsoft/vscode/blob/master/build/gulpfile.extensions.js#L67
1. https://github.com/Microsoft/vscode-nls-dev/blob/master/src/tests/analyze.tests.ts#L11

you will have a better idea of what is the shape of the .json file that is needed. It's not sufficient to just have the i18n folder as you have.

I have a basic version (doesn't hook into the build pipeline) that will hopefully demystify some of the magic that vscode-nls and vscode-nls-dev is doing. Take a look at https://github.com/vazexqi/vscode-extension-samples/tree/master/i18n-sample (I might submit this as a PR if I hook into the whole nls-dev pipeline of gulp tasks)

![demo](https://user-images.githubusercontent.com/54414/27989560-e175bd68-63ef-11e7-8cdd-f231e626dfd0.gif)

Also, as @michelkaporin pointed out, you want to be *very* careful to ensure that nls.config is called during the activation of your extension before nls.loadMessageBundle (remember this could happen during import statements from modules you depend on). See https://github.com/vazexqi/vscode-extension-samples/blob/master/i18n-sample/src/extension.ts

IMO, the vscode-nls and vscode-nls-dev combination seems quite heavyweight for most use-cases. If you are sending stuff over to Transifex for translations, this overhead might be necessary.

You might be better off just rolling your own implementation of a simple key-value .json file. The trick to this is to just read `process.env.VSCODE_NLS_CONFIG` to see what locale VS Code is run with and then just load the right bundle.

On a separate note, @dbaeumer and @michelkaporin - why is the .json file that you expect for vscode-nls keyed by position rather than by message string? This seems very unintuitive and requires lots of transformation (including the complicated JS source manipulation at https://github.com/Microsoft/vscode-nls-dev/blob/master/src/lib.ts#L642). Why not just follow the format that you use for the top-level package.nls.json and have them be key-values pairs in the .json file?

**Comment by leftstick** [comment]
@vazexqi , thanks man. I think the issue shall be closed since your example just awesome

**Comment by dbaeumer** [comment]
@vazexqi late answer: performance and memory consumption. If you have thousands of messages (which we do in VS Code) then this starts to matter.
