### ISSUE TITLE
Problem with lsp-log-streaming-sample example

### ISSUE THREAD

**Issue by VladD2** [microsoft/vscode-extension-samples#242]
Trying to run the [lsp-log-streaming-sample](https://github.com/microsoft/vscode-extension-samples/tree/master/lsp-log-streaming-sample) example. Performing the steps described in "Running the Sample". But no message appears in the "streams".

**Comment by octref** [comment]
Not sure what you did differently, but this is working for me:

![image](https://user-images.githubusercontent.com/4033249/72166132-fda2c480-33c8-11ea-9c4d-ea4efbf44594.png)

What do you see? If you run the command "Developer: Open webview developer tools", any error there?

**Comment by IWANABETHATGUY** [comment]
main.js:563 Refused to load the script 'vscode-resource:/c%3A/Users/xxx/.vscode/extensions/octref.lsp-inspector-webview-0.0.2/dist/webview/js/chunk-vendors.3486d69f.js' because it violates the following Content Security Policy directive: "script-src vscode-webview-resource: 'unsafe-inline'". Note that 'script-src-elem' was not explicitly set, so 'script-src' is used as a fallback.

(anonymous) @ main.js:563
app.39c3645b.css:1 Failed to load resource: net::ERR_UNKNOWN_URL_SCHEME
chunk-vendors.c05bff2f.css:1 Failed to load resource: net::ERR_UNKNOWN_URL_SCHEME
app.b1391153.js:1 Failed to load resource: net::ERR_UNKNOWN_URL_SCHEME
chunk-vendors.3486d69f.js:1 Failed to load resource: net::ERR_UNKNOWN_URL_SCHEME
index.html:1 Refused to load the script 'vscode-resource:/c%3A/Users/xxx/.vscode/extensions/octref.lsp-inspector-webview-0.0.2/dist/webview/js/app.b1391153.js' because it violates the following Content Security Policy directive: "script-src vscode-webview-resource: 'unsafe-inline'". Note that 'script-src-elem' was not explicitly set, so 'script-src' is used as a fallback.

this is my error stack

**Comment by mjbvz** [comment]
Closing this as there has not been follow up from the original poster
