### ISSUE TITLE
Is it possible to call window.print() from VSCode extension?

### ISSUE THREAD

**Issue by greybax** [microsoft/vscode-extension-samples#320]
I have standalone app which has "Print" html  button. And I'm rendering this page also into my VSCode extension. But when I click on print button doesn't happend into VSCode. 

Also I've tried to emulate print html mechanism into VSCode DevConsole, but getting error:
![image](https://user-images.githubusercontent.com/3235047/85081000-99f2a380-b17f-11ea-8e45-26c8b2a92e37.png)

Is it possible somehow to print html page which is rendering into webview of my VSCode extension?

**P.S.** I've seen this issue: [WebView optionally add "allow-modals" to iframe sandbox options #67109
](https://github.com/Microsoft/vscode/issues/67109) but not sure is it possible somehow to create an adapter for print the webview page into VSCode extension

**Comment by mjbvz** [comment]
No, we don't support printing from webviews and do not have plans to add support.

You could try using a native module to control printing

**Comment by greybax** [comment]
@mjbvz  thanks for your answer. Could you please specify what is "native module"? Do you mean this node module https://github.com/tojocky/node-printer?

**Comment by mjbvz** [comment]
yes

**Comment by Mogztter** [comment]
> No, we don't support printing from webviews and do not have plans to add support.
> You could try using a native module to control printing

I think it would be extremely useful to print a webview to PDF.
As far as I know it's not possible to do that using a native module because it's a browser feature, right?

With project like [Paged.js](https://www.pagedjs.org/documentation/) (based on W3C specifications) it's possible to produce high-quality PDF documents using web technologies (and especially the print to PDF feature provided by browsers).

A typical use case, would be to generate a printable web page from a lightweight markup language such as AsciiDoc or Markdown and use the print to PDF feature to produce a PDF.

I guess it's still possible to run an headless browser outside of VS Code (using Puppeteer) to generate a PDF but it seems extremely heavy as a workaround.

@mjbvz Could you please give us some insights about this restriction?

Thanks!

**Comment by mjbvz** [comment]
Nothing to add besides printing is not a use case we feel is important enough to support or maintain. Your extension can use whatever tools it needs to print, but it's not something we are going to put into core

**Comment by Mogztter** [comment]
I think it's unfortunate but I guess it's what it's.
Let me know if you change your mind 😉
