### ISSUE TITLE
How to get relative file path in server?

### ISSUE THREAD

**Issue by glen-84** [Microsoft/vscode-extension-samples#34]
How would I get a file's relative path (to the root folder) from the server side of my extension?

**Comment by egamma** [comment]
@glen-84 are you implementing a language server and are now migrating to multiple-root folder support? If yes, what extension do you want to migrate?

Have you seen the migration guide https://github.com/Microsoft/vscode/wiki/Extension-Authoring:-Adopting-Multi-Root-Workspace-APIs? Here is a sample https://github.com/Microsoft/vscode-extension-samples/blob/master/lsp-multi-root-sample/server/src/server.ts

We also have a slack channel for questions like this. @seanmcbreen has the details and can invite you.

**Comment by glen-84** [comment]
> are you implementing a language server and are now migrating to multiple-root folder support?

Yes.

> If yes, what extension do you want to migrate?

https://marketplace.visualstudio.com/items?itemName=glen-84.sass-lint

> Can you describe your scenario a bit more then we can give a more specific answer.

I need to remove/replace the `workspaceRoot` usage here: https://github.com/glen-84/vscode-sass-lint/blob/master/sass-lint-server/src/server.ts#L202

> Have you seen the migration guide

Yes, I have read it, thanks.

> We also have a slack channel for questions like this. @seanmcbreen has the details and can invite you.

I tried Gitter, but there was no reply before I logged out. I would appreciate the Slack invite.

Is there something like `workspace.getWorkspaceFolder(uri)` on the "server" side? Or would I have to send a client request or similar?

Thanks.

**Comment by egamma** [comment]
If I understand it properly you are working paths relative to the language server's current working directory? In the single root folder case the current working directory of the server corresponds to the workspace folder. When you have multiple root folders open, then this is no longer the case, since the above assumption is only valid for the first opened root folder, which starts the server. For this reason you have to be careful with relative path names when you share the server in the multi-folder setup. 

To make sure that the problem is exposed when you have >1 folder, you can start the server in another directory as is done in the code below. There the server is started in the folder where VS Code is launched from:
https://github.com/Microsoft/vscode-tslint/blob/08f2f1d17d3c17bec487dffe618060ca2141bf95/tslint/extension.ts#L149

For vscode-tslint I therefore only work with absolute path names in the language server and I resolve the paths on the client. 

Adding @dbaeumer for providing his advice on how to best migrate your scenario.

**Comment by egamma** [comment]
@glen-84 this is the slack channel link: https://vscode-dev-community.slack.com/join/shared_invite/enQtMjIxOTgxNDE3NzM0LWU5M2ZiZDU1YjBlMzdlZjA2YjBjYzRhYTM5NTgzMTAxMjdiNWU0ZmQzYWI3MWU5N2Q1YjBiYmQ4MzY0NDE1MzY

**Comment by dbaeumer** [comment]
@glen-84 there is no request right now that resolves a workspace folder for a URI. This is mainly to make it easier for other clients to implement the new requests. However if you feel strongly about it then please open an issue and we can consider it. The workspace folder support in the protocol is still proposed. 

To address your issue you can do the following:

- register a workspace folder change listener. This can be done on the server side using the `connection.workspace._onDidChangeWorkspaceFolders` event source. This is more or less the same than the VS Code API.
- use `connect.workspace.getWorkspaceFolders` to get the initial list of workspace folder or use the `workspaceFolders` property on the initialization parameters. When proposed request/response are enable the params in the initialize request will contain a list of workspace folders.
- the full documentation of the new workspace folder request / response pairs can be found here: https://github.com/Microsoft/vscode-languageserver-node/blob/master\protocol\src\protocol.workspaceFolders.proposed.md#L1
 there are two things you can do assuming that you use the proposed API for workspace folders on both the client and the server (as described in the example):

**Comment by seanmcbreen** [comment]
@glen-84 here is a link to the slack channel

https://vscode-dev-community.slack.com/join/shared_invite/enQtMjIxOTgxNDE3NzM0LWU5M2ZiZDU1YjBlMzdlZjA2YjBjYzRhYTM5NTgzMTAxMjdiNWU0ZmQzYWI3MWU5N2Q1YjBiYmQ4MzY0NDE1MzY

**Comment by glen-84** [comment]
Thanks for the Slack invitations. I've joined (glen-84).

[Here](https://github.com/AtomLinter/linter-sass-lint/blob/6f441793f04db819e31787f41236c5a61d34a96c/lib/main.coffee#L59) is the relevant code in the Atom extension. It looks like Atom has a [relativizePath](https://atom.io/docs/api/v1.15.0/Project#instance-relativizePath) function.

@dbaeumer,

I'm not really sure what you're suggesting. How does having a list of workspace folders give me the relative path of the active file?

Let's look at an example:

**Active file**: `/a/b/c.ext`

**Root folders:**
1. `/a`            (contains folder `b`)
2. `/a/b`

If the active file was opened via:

* Root folder 1, then the relative path would be `b/c.ext`
* Root folder 2, then the relative path would be `c.ext`

I wouldn't know which one to use.

Do you track from which root folder the active file was opened?

I don't know how I should handle this, so any help would be appreciated.

**Comment by glen-84** [comment]
> If I understand it properly you are working paths relative to the language server's current working directory?

Relative to the `rootPath`.

**Comment by glen-84** [comment]
Couldn't `onDidChangeContent` and `onDidSave` provide a context object with the workspace folder path and other details?

**Comment by dbaeumer** [comment]
@glen-84 we don't track from which root folder the file got opened so this information is not available. We decided to not handle them different since a c.ext opened from /a should not give different results than opened from /a/b

In the example it is up to the language server to decide if there is one root to handle or two roots to handle. From the languages I looked at so far we always decided to only (from a language perspective) treat such setups as a single root setup have only /a as a root folder.

**Comment by glen-84** [comment]
@dbaeumer,

Are you suggesting the following?:

1. Get and maintain the list of open workspace folders
2. To determine the relative path:
    * Sort the open workspace folders by path length (shortest first)
    * Iterate and check if the active file path starts with the workspace folder path
    * Break after the first match
    * Get the relative path from the matched workspace folder to the active file

So in my example above, folder `/a` would be sorted first, and the active file begins with it, so it would be returned. The relative path would then be `b/c.ext` regardless of whether it was opened from `/a` or `/a/b`.

If that's what you mean, then I guess it can work, although it seems like extra work (having to search each time, instead of just having that information available in the event).

Please confirm.

**Comment by dbaeumer** [comment]
@glen-84 yes that is what I am suggesting. I think we can't provide that information in an event since we don't know (in the case of nested folders) what the strategy is. 

There is code that does what you need here: https://github.com/Microsoft/vscode-extension-samples/blob/master/lsp-multi-server-sample/client/src/extension.ts#L13

It is running on the client but can easily be adopted to the server if necessary.

**Comment by glen-84** [comment]
Thanks for the help. 👍

**Comment by glen-84** [comment]
> register a workspace folder change listener. This can be done on the server side using the connection.workspace._onDidChangeWorkspaceFolders event source.

Where can I find a simple example of this? I can't get it to work.

**Comment by dbaeumer** [comment]
@glen-84 I have updated the example `lsp-multi-root-sample` to demo this. Have a look at the initialized hook in the server.ts file.
