### ISSUE TITLE
lsp-sample not working from VSIX package

### ISSUE THREAD

**Issue by rbasniak** [microsoft/vscode-extension-samples#432]
Hello,

Repro steps:

1. clone the repository
2. open  `lsp-sample` in VSCODE
3. `npm install`
4. `npm run compile`
5. start debug
6. extension is working
7. close vscode debug window
8. `npm install vsce -g`
9. change publisher name in `package.json`
10. `vsce package`
11. `Ctrl+P` -> `Extensions: Install from VSIX...`
12. selected the generated VSIX file
13. extension is installed with sucess
14. open a text file
15. extension doesn't work

It seems that the language server is not being started for some reason. I tried with other lsp samples and the same happens. They don't work within the VSIX package. Is there any step I am missing?

Thanks in advance... 
Rodrigo

**Comment by andrew-mclachlan** [comment]
I am seeing this too. I followed the exact steps. I can see the extension listed as installed, but it's not working when installed using VSIX package.

**Comment by andrew-mclachlan** [comment]
I found that the problem was a package not being included in the VSIX. The following issue highlights the problem: https://github.com/microsoft/vscode-extension-samples/issues/412

I found that when I launched VSCode and looked in the Developer Tools, I could see an error due to lru-cache not being found.

Modifying my vscodeignore as per the Issue above solved my problem and I could use the extension.

--- a/.vscodeignore
+++ b/.vscodeignore
@@ -11,7 +11,8 @@ client/node_modules/**
 !client/node_modules/vscode-languageclient/**
 !client/node_modules/vscode-languageserver-protocol/**
 !client/node_modules/vscode-languageserver-types/**
-!client/node_modules/semver/**
+!client/node_modules/{minimatch,brace-expansion,concat-map,balanced-match}/**
+!client/node_modules/{semver,lru-cache,yallist}/**

**Comment by dbaeumer** [comment]
Updated the example to have a correct `.vscodeignore` file
