### ISSUE TITLE
So how do I build a LSP extension?

### ISSUE THREAD

**Issue by shadycuz** [microsoft/vscode-extension-samples#447]
So this is how the example LSP guide starts...

> First, Language Servers are usually implemented in their native programming languages, and that presents a challenge in integrating them with VS Code, which has a Node.js runtime.

Oh cool, so the example extension is not going to use Node.js right? That would be pointless...

Also in the guide...

> In the example, the server is also implemented in TypeScript and executed using Node.js. Since VS Code already ships with a Node.js runtime, there is no need to provide your own, unless you have specific requirements for the runtime.

Just going to leave this here...
![image](https://user-images.githubusercontent.com/17090999/121807421-10ef3a80-cc22-11eb-95ea-93a9111389c1.png)

**Comment by vivekmalneedi** [comment]
The samples use nodejs since thats what Microsoft supports with their libraries. You can modify `serverOptions` from the [client sample](https://github.com/microsoft/vscode-extension-samples/blob/a92db32ca1fba751efc795623d089afa03a5572c/lsp-sample/client/src/extension.ts#L29), to run an executable instead. As seen in [vscode-languageclient](https://github.com/microsoft/vscode-languageserver-node/blob/3076e79c8e6569fcdeac61446cbffe5a20ff8034/client/src/node/main.ts#L124) you can pass in an executable, a node module (as is done in the sample), or a child process.

**Comment by shadycuz** [comment]
@vivekmalneedi Would be really helpful if the example showed docker or anything but using the default runtime, because most LSP extension authors will probably have to install some kinda runtime on the fly. 

I'm pretty sure pylance the python LSP extension uses docker but its closed source. I mean I'm guessing I could just call the docker executable? but I was thinking their was a more robust way of doing it that assure docker would be installed or something.

**Comment by vivekmalneedi** [comment]
I have no idea how Microsoft's extensions work but I've used a multitude of open-source language servers and I haven't seen any that use docker. In general the users are developers that shouldn't have much trouble installing runtime dependencies like python, node, language specific tooling etc.
