### ISSUE TITLE
Remove onDidChange file watcher

### ISSUE THREAD

**Issue by JustinGrote** [microsoft/vscode-extension-samples#455]
@connor4312 I don't think this is required anymore with the new direction to subscribe to the vscode events for document changes, it confused me for a bit.
https://github.com/microsoft/vscode-extension-samples/blob/8fdf822985243c42aa7ed922a9a6c1fc5540c478/test-provider-sample/src/extension.ts#L114

**Comment by JustinGrote** [comment]
I guess related, what if a test file changes via activity not currently in a vscode window? Seems to me the current updater won't detect it, so maybe this needs to be preserved and rewired back up to discovery? And if a vscode window is open, if this is wired up too how do you prevent double re-discovery?

**Comment by connor4312** [comment]
> what if a test file changes via activity not currently in a vscode window? Seems

That is actually what the file watcher is for. You're correct that document changes will generally pick up changes made inside a VS Code editor, and the watcher will pick up any changes that happen outside of there.

Double/re-discovery is not really a big problem. It's not optimally efficient, but the sample is fast enough and an extension could optimize it further if they wanted (e.g. by keeping a quick hash of the file contents and seeing if it's changed or not since the last discovery).

**Comment by JustinGrote** [comment]
@connor4312 Thats my point though, at least currently the onDidChange filehander contentChange event isn't wired to anything anymore, it just fires into the ether, unless I'm missing where it's wired up to.

**Comment by connor4312** [comment]
Oh, right! Misread the issue and/or the code 😄
