### ISSUE TITLE
What happens if `"engines"` in `client/package.json` does not match `"engines"`in `./package.json`?

### ISSUE THREAD

**Issue by hamirmahal** [microsoft/vscode-extension-samples#532]
For example, [`lsp-sample/package.json`](https://github.com/microsoft/vscode-extension-samples/blob/main/lsp-sample/package.json#L16-L18) has

```
"engines": {
		"vscode": "^1.43.0"
	},
```

but [`lsp-sample/client/package.json`](https://github.com/microsoft/vscode-extension-samples/blob/main/lsp-sample/client/package.json#L12-L14) has

```
	"engines": {
		"vscode": "^1.52.0"
	},
```

What ramifications are there to having a mismatch in the `"engines"` property of `./package.json` and `./client/package.json`?

**Comment by dbaeumer** [comment]
The LSP client double checks the engine when a client is started. If it doesn't match the client will throw an exception. See code here: https://github.com/microsoft/vscode-languageserver-node/blob/e3fa8c7fb9eaab718124c6314beb2fca4ba43f8a/client/src/node/main.ts#L25

Since the sample is never packaged as an extension the engine filed in the sample does usually not matter. However I will align them to make this less confusable.

**Comment by dbaeumer** [comment]
Updated the dependencies.

**Comment by hamirmahal** [comment]
Thanks for the clarification, Dirk!
