### ISSUE TITLE
Signing out?

### ISSUE THREAD

**Issue by lewisl9029** [microsoft/vscode-extension-samples#548]
Hi there, in the [authentication sample](https://github.com/microsoft/vscode-extension-samples/blob/main/authenticationprovider-sample/src/authProvider.ts#L133), it mentions that the `removeSession()` method of the provider gets called when a user signs out. 

However, I don't see anything in the [authentication namespace](https://code.visualstudio.com/api/references/vscode-api#authentication) to use to implement a sign out command. Should there be a removeSession() function in addition to getSession() and hasSession()?

In my extension, I'm just keeping a reference to the authenticationProvider instance and calling removeSession on it directly, not sure if this is the intended approach? 

Any assistance would be appreciated! Thanks!

**Comment by TylerLeonhardt** [comment]
We don't have a removeSession because we wanted the logging in and logging out of an account to have consistent UX across all auth providers.

The only way to trigger a removeSession is by the user using the Sign Out option here:
![image](https://user-images.githubusercontent.com/2644648/156082669-09eaab50-ab57-4d79-bff8-c2a470f04414.png)
