### ISSUE TITLE
Deprecate older extension versions on marketplace

### ISSUE THREAD

**Issue by KartikM123** [microsoft/vscode-extension-samples#576]
I wanted to prevent users from using older versions of my vscode extension (eg. >1 year old) to make it easier for me to get rid of older dependencies. Is there any way to prevent users from downloading certain versions of my extension?

**Comment by isidorn** [comment]
@KartikM123 Marketplace currently does not support deprecation, that might come in the future.

I suggest that you go ahead a get rid of older dependencies, you should assume that your users are using the latest extension version.
If you still get users on older versions complaining we can explicitly remove older versions of your extension from the marketplace. If that is the case just comment here and I will see it. 

Since no action planned from our side, and there is already an issue for extension deprecation on the MP side I will go ahead and close this. Thanks
