### ISSUE TITLE
Need Information on Implementing window.showDocument Inside CodeAction "Quick Fix"

### ISSUE THREAD

**Issue by david-pa** [microsoft/vscode-extension-samples#684]
Last week I submitted issue #678 and the response I got wasn't very clear.

I am submitting this issue to get some additional context on `window.showDocument` and if it applies to my situation. All I am trying to do is provide a "quick fix" option that is capable of redirecting the user directly to some documentation page via a URL. I was told that `window.showDocument` could accomplish this task, but there isn't much context in the available documentation that suggests how it should be implemented. 

I was under the impression that it may be possible to include `window.showDocument` in the `Command?:` field of a `CodeAction`, using `window.showDocument` as the Command's identifier string, but my attempts at testing that theory haven't been successful. Is that a valid method to consider?

If I have CodeActions setup and Quick Fixes already showing up in VSCode, what additional code should I be adding to the server/client to make `window.showDocument` possible? Sample code of any kind would be extremely useful.

This was the additional comment I added on the previous issue, which was not responded to:

> Could you clarify how to implement this sort of action via a Code Action on the LSP? I have existing code actions that are sent out as quick fixes for certain lines, and I'd like to also include a quick fix for documentation via this "Show Document" request you've suggested.

> Code Actions when constructed have different fields based on what data needs to be returned. For instance, there's a edit?: field for making changes to the document and command?: for executing commands. However, it's my understanding that command?: values are only meant to reference pre-registered/hard-coded identifiers. Is it possible to show a document within a code action "quick fix", or is it meant to be used another way? How does it go from the server over to the client? This is not very clear in the documentation.

> Is there sample code that exists that illustrates the specifics of how to implement this?

**Comment by dbaeumer** [comment]
The way how to implement this is the following:

- use a command inside the quick fix
- register the server as a handler of that command
- Use the LSP request https://microsoft.github.io/language-server-protocol/specifications/lsp/3.17/specification/#window_showDocument to open the document.

You might want to look here how this is done for ESLint: 

https://github.com/microsoft/vscode-eslint/blob/705f5f5d86aab57b16c36e31f229549883d6a37f/server/src/eslintServer.ts#L820

Note that ESLint still uses a custom message to open the document instead of the new message that got added in 3.17.
